import type { ContentFormatPreset } from '../../api/models';

const FORMAT_BUDGETS: Record<string, ContentFormatPreset['generation_budget']> = {
  reddit_story: { max_speakers_for_draft: 1, max_lines_for_60s_draft: 6, max_words_per_line: 12, max_total_words: 84, target_segment_count: 6, recommended_tts_mode: 'fallback_or_cached_clone', draft_duration_range_sec: [30, 50], final_duration_range_sec: [35, 75], section_line_counts: { hook: 1, setup: 1, escalation: 1, twist: 1, aftermath: 1, cta: 1 } },
  character_dialogue: { max_speakers_for_draft: 2, max_lines_for_60s_draft: 7, max_words_per_line: 10, max_total_words: 70, target_segment_count: 7, recommended_tts_mode: 'fallback_or_cached_clone', draft_duration_range_sec: [20, 45], final_duration_range_sec: [20, 60], section_line_counts: { hook: 1, conflict: 1, escalation: 2, payoff: 2, cta: 1 } },
  podcast_clip: { max_speakers_for_draft: 2, max_lines_for_60s_draft: 6, max_words_per_line: 12, max_total_words: 72, target_segment_count: 6, recommended_tts_mode: 'fallback_or_cached_clone', draft_duration_range_sec: [25, 50], final_duration_range_sec: [30, 75], section_line_counts: { hook: 1, question: 1, insight: 1, example: 1, takeaway: 1, cta: 1 } },
  debate_format: { max_speakers_for_draft: 3, max_lines_for_60s_draft: 7, max_words_per_line: 11, max_total_words: 77, target_segment_count: 7, recommended_tts_mode: 'fallback_or_cached_clone', draft_duration_range_sec: [30, 55], final_duration_range_sec: [30, 70], section_line_counts: { hook: 1, claim: 1, rebuttal: 1, counterexample: 1, tension: 1, verdict: 1, cta: 1 } },
  meme_news_reaction: { max_speakers_for_draft: 1, max_lines_for_60s_draft: 5, max_words_per_line: 10, max_total_words: 50, target_segment_count: 5, recommended_tts_mode: 'fallback_or_cached_clone', draft_duration_range_sec: [15, 35], final_duration_range_sec: [15, 45], section_line_counts: { headline: 1, reaction: 1, implication: 1, payoff: 1, cta: 1 } },
  educational_short: { max_speakers_for_draft: 1, max_lines_for_60s_draft: 6, max_words_per_line: 12, max_total_words: 72, target_segment_count: 6, recommended_tts_mode: 'fallback_or_cached_clone', draft_duration_range_sec: [20, 45], final_duration_range_sec: [20, 60], section_line_counts: { hook: 1, misconception: 1, explanation: 1, example: 1, takeaway: 1, cta: 1 } },
  multi_speaker_skit: { max_speakers_for_draft: 3, max_lines_for_60s_draft: 6, max_words_per_line: 9, max_total_words: 54, target_segment_count: 6, recommended_tts_mode: 'fallback_or_cached_clone', draft_duration_range_sec: [25, 50], final_duration_range_sec: [25, 70], section_line_counts: { premise: 1, role_setup: 1, exchange: 2, punchline: 1, tag: 1 } },
};

export const FALLBACK_CONTENT_FORMATS: ContentFormatPreset[] = [
  {
    id: 'reddit_story',
    display_name: 'Reddit Story',
    short_description: 'First-person narrated story built for retention.',
    best_use_case: 'Confessions, workplace drama, relationship twists, and comment-bait narration.',
    purpose: 'Narrated story with hook, setup, escalation, twist, aftermath, and viewer question.',
    ideal_duration_range_sec: [35, 75],
    supported_speaker_count: [1, 2],
    default_speaker_roles: ['Narrator'],
    tone_options: ['confessional', 'suspenseful', 'dryly funny'],
    pacing_rules: ['Open with a concrete surprise', 'Raise stakes every 1-2 lines'],
    section_structure: ['hook', 'setup', 'escalation', 'twist', 'aftermath', 'cta'],
    caption_style_hints: ['Short cliffhanger chunks', 'Emphasize the reveal'],
    default_metadata_hints: { title: null, description: null, hashtags: ['#storytime'], cta: 'comment with your verdict' },
    prompt_guidance: ['Write in first person unless asked otherwise'],
    validation_rules: ['1 narrator, optional reaction speaker'],
    speaker_model: 'narrator_plus_optional_reaction',
    generation_budget: FORMAT_BUDGETS.reddit_story,
  },
  {
    id: 'character_dialogue',
    display_name: 'Character Dialogue',
    short_description: 'Two or more characters with clear personalities and conflict.',
    best_use_case: 'Recurring characters, reaction duos, scripted arguments, and creator mascots.',
    purpose: 'Distinct character voices escalate a conflict into a punchline or payoff.',
    ideal_duration_range_sec: [20, 60],
    supported_speaker_count: [2, 4],
    default_speaker_roles: ['Character A', 'Character B'],
    tone_options: ['deadpan', 'chaotic', 'sarcastic'],
    pacing_rules: ['Alternate speakers', 'Every reply responds to the prior line'],
    section_structure: ['hook', 'conflict', 'escalation', 'payoff', 'cta'],
    caption_style_hints: ['Speaker-labeled captions', 'Keep punchlines short'],
    default_metadata_hints: { title: null, description: null, hashtags: ['#dialogue'], cta: 'follow for the next argument' },
    prompt_guidance: ['Give each speaker a recognizable stance'],
    validation_rules: ['2-4 speakers', 'dialogue must alternate naturally'],
    speaker_model: 'dialogue',
    generation_budget: FORMAT_BUDGETS.character_dialogue,
  },
  {
    id: 'podcast_clip',
    display_name: 'Podcast Clip',
    short_description: 'Conversational short that feels clipped from a longer discussion.',
    best_use_case: 'Founder clips, expert explainers, interviews, and thought-leadership snippets.',
    purpose: 'Cold-open claim, host question, guest insight, example, and takeaway.',
    ideal_duration_range_sec: [30, 75],
    supported_speaker_count: [2, 3],
    default_speaker_roles: ['Host', 'Guest'],
    tone_options: ['insightful', 'curious', 'direct'],
    pacing_rules: ['Start with a cold-open claim', 'Guest gives concrete examples'],
    section_structure: ['hook', 'question', 'insight', 'example', 'takeaway', 'cta'],
    caption_style_hints: ['Quote-worthy chunks', 'Emphasize the guest insight'],
    default_metadata_hints: { title: null, description: null, hashtags: ['#podcastclip'], cta: 'save this clip' },
    prompt_guidance: ['Make the guest sound specific'],
    validation_rules: ['host plus at least one guest'],
    speaker_model: 'host_guest',
    generation_budget: FORMAT_BUDGETS.podcast_clip,
  },
  {
    id: 'debate_format',
    display_name: 'Debate Format',
    short_description: 'Opposing viewpoints with clear contrast and tension.',
    best_use_case: 'Pros/cons, hot takes, policy questions, and product choices.',
    purpose: 'Claim, rebuttal, counterexample, tension beat, and verdict or open question.',
    ideal_duration_range_sec: [30, 70],
    supported_speaker_count: [3, 3],
    default_speaker_roles: ['Moderator', 'Speaker A', 'Speaker B'],
    tone_options: ['sharp', 'balanced', 'combative'],
    pacing_rules: ['Frame quickly', 'Both sides must disagree'],
    section_structure: ['hook', 'claim', 'rebuttal', 'counterexample', 'tension', 'verdict', 'cta'],
    caption_style_hints: ['Label sides clearly', 'Verdict/open question card'],
    default_metadata_hints: { title: null, description: null, hashtags: ['#debate'], cta: 'drop your verdict' },
    prompt_guidance: ['Make both sides plausible'],
    validation_rules: ['exactly 3 speakers'],
    speaker_model: 'moderated_debate',
    generation_budget: FORMAT_BUDGETS.debate_format,
  },
  {
    id: 'meme_news_reaction',
    display_name: 'Meme/News Reaction',
    short_description: 'Fast topical reaction with absurd implication and punchline.',
    best_use_case: 'News riffs, trend reactions, brand commentary, and meme response clips.',
    purpose: 'Headline, reaction, absurd implication, punchline, and comment prompt.',
    ideal_duration_range_sec: [15, 45],
    supported_speaker_count: [1, 2],
    default_speaker_roles: ['Narrator', 'Reaction'],
    tone_options: ['snarky', 'surprised', 'absurd'],
    pacing_rules: ['First line reads like a headline', 'Payoff should be concise'],
    section_structure: ['headline', 'reaction', 'implication', 'payoff', 'cta'],
    caption_style_hints: ['Headline card', 'Big reaction captions'],
    default_metadata_hints: { title: null, description: null, hashtags: ['#newsreaction'], cta: 'send this to a friend' },
    prompt_guidance: ['Name the concrete topic immediately'],
    validation_rules: ['1-2 speakers'],
    speaker_model: 'host_reaction',
    generation_budget: FORMAT_BUDGETS.meme_news_reaction,
  },
  {
    id: 'educational_short',
    display_name: 'Educational Short',
    short_description: 'One idea explained quickly and memorably.',
    best_use_case: 'How-tos, product education, creator tips, workflows, and technical explainers.',
    purpose: 'Correct a misconception, explain the mechanism, show an example, and leave a takeaway.',
    ideal_duration_range_sec: [20, 60],
    supported_speaker_count: [1, 2],
    default_speaker_roles: ['Teacher'],
    tone_options: ['clear', 'practical', 'friendly'],
    pacing_rules: ['Open with a misconception', 'Include one concrete example'],
    section_structure: ['hook', 'misconception', 'explanation', 'example', 'takeaway', 'cta'],
    caption_style_hints: ['Short concept labels', 'Takeaway card'],
    default_metadata_hints: { title: null, description: null, hashtags: ['#education'], cta: 'save this for later' },
    prompt_guidance: ['Make the takeaway actionable'],
    validation_rules: ['1 teacher or teacher/student pair'],
    speaker_model: 'teacher',
    generation_budget: FORMAT_BUDGETS.educational_short,
  },
  {
    id: 'multi_speaker_skit',
    display_name: 'Multi-Speaker Skit',
    short_description: 'Short scene with multiple speakers and visual rhythm.',
    best_use_case: 'Office scenes, creator teams, group chats, chaotic explainers, and ensemble jokes.',
    purpose: 'Premise, role setup, chaotic exchange, punchline, and tag.',
    ideal_duration_range_sec: [25, 70],
    supported_speaker_count: [3, 5],
    default_speaker_roles: ['Character A', 'Character B', 'Character C'],
    tone_options: ['chaotic', 'deadpan', 'satirical'],
    pacing_rules: ['Give each role a job', 'Use a final tag after the punchline'],
    section_structure: ['premise', 'role_setup', 'exchange', 'punchline', 'tag'],
    caption_style_hints: ['Speaker-labeled short captions', 'Tag caption'],
    default_metadata_hints: { title: null, description: null, hashtags: ['#skit'], cta: 'follow for part two' },
    prompt_guidance: ['Make the cast sound distinct'],
    validation_rules: ['3-5 speakers'],
    speaker_model: 'ensemble',
    generation_budget: FORMAT_BUDGETS.multi_speaker_skit,
  },
];

export const findFormat = (formats: ContentFormatPreset[], id: string) =>
  formats.find((format) => format.id === id) || formats.find((format) => format.id === 'educational_short') || formats[0];

export const durationLabel = (format: ContentFormatPreset) =>
  `${format.ideal_duration_range_sec[0]}-${format.ideal_duration_range_sec[1]}s`;

export const speakerCountLabel = (format: ContentFormatPreset) => {
  const [min, max] = format.supported_speaker_count;
  return min === max ? `${min} speaker${min === 1 ? '' : 's'}` : `${min}-${max} speakers`;
};
