# services/platforms/base.py
from typing import Protocol, Iterable, Dict, Any, Optional

class PlatformClient(Protocol):
    def fetch_creator(self, creator_external_id: str) -> Dict[str, Any]: ...
    def fetch_latest_videos(self, creator_external_id: str, page_token: Optional[str], limit: int) -> Dict[str, Any]: ...
    def fetch_video_stats(self, video_ids: list[str]) -> Dict[str, Any]: ...
    def fetch_comments(self, video_id: str, cursor: Optional[str], limit: int) -> Dict[str, Any]: ...
