services:
  api:
    build: ./backend
    env_file: .env
    depends_on: [redis]
  worker:
    build: ./backend
    command: celery -A app.celery_app.celery worker -Q crawl -O fair --concurrency=4
    env_file: .env
    depends_on: [redis]
  beat:
    build: ./backend
    command: celery -A app.celery_app.celery beat
    env_file: .env
    depends_on: [redis]
  redis:
    image: redis:7
